[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = espidf
board_build.partitions = partitions.csv
monitor_speed = 115200
build_flags =
    -DCONFIG_MCPWM_SUPPRESS_DEPRECATE_WARN
    -Wno-error=unused-parameter
